---
  - name: Create User-Bridged Network
    become: yes
    become_user: root
    docker_network:
      name: flask-app-network

  - name: Run Dockerized Flask Application
    become: yes
    become_user: root
    docker_container:
      name: sayari-flask-app
      image: kabirgupta3/sayari-flask-app:v1
      state: started
      detach: yes
      networks:
      - name: flask-app-network
      purge_networks: yes
      ports:
      - "5000:5000"
